#!/bin/bash

IS_CONNECTED=$(kdeconnect-cli -a --id-only 2>&1)
if [[ "$IS_CONNECTED" != "No devices found" ]]; then
    STATUS=$(qdbus org.kde.kdeconnect /modules/kdeconnect/devices/4c522739f00612bd org.kde.kdeconnect.device.battery.charge)
    echo "${STATUS}%"
    echo "${STATUS}%"
    echo ""
fi
